# Generated by Django 2.2.3 on 2019-07-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_contact', models.CharField(choices=[('Company_Enterprise', 'Company/Enterprise'), ('Municipality', 'Municipality'), ('School_college', 'School/College'), ('Hospital', 'Hospital'), ('Individual', 'Individual'), ('Other', 'Other')], default='Company_Enterprise', max_length=30)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
