# Generated by Django 2.2.3 on 2019-07-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_form',
            name='subject_matter',
            field=models.CharField(choices=[('Licensing', 'Licensing'), ('Employment', 'Employment'), ('ColorADD_social', 'ColorADD Social'), ('Funds_donations', 'Funds/Donations'), ('Other_subject', 'Other subject')], default='Licensing', max_length=30),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='text_message',
            field=models.TextField(default=''),
        ),
    ]
